Repository CHUMneuroepilepsie/VR_Polytechnique, pull requests merged in 2022-10, with the labels that each got.

#9 Mouvement continue et simulateur sans casque
  VR_Polytechnique/.vsconfig
  VR_Polytechnique/Assets/Assets/Controller.prefab
  VR_Polytechnique/Assets/Assets/Controller.prefab.meta
  VR_Polytechnique/Assets/Scenes/Camera&Movement.unity
  VR_Polytechnique/Assets/Scenes/Camera&Movement.unity.meta
  VR_Polytechnique/Assets/Scripts/HMDInfoManager.cs
  VR_Polytechnique/Assets/Scripts/HMDInfoManager.cs.meta
  VR_Polytechnique/Assets/XR/Loaders/Mock HMD Loader.asset
  VR_Polytechnique/Assets/XR/Loaders/Mock HMD Loader.asset.meta
  VR_Polytechnique/Assets/XR/Settings/Mock HMD Build Settings.asset
  VR_Polytechnique/Assets/XR/Settings/Mock HMD Build Settings.asset.meta
  VR_Polytechnique/Assets/XR/XRGeneralSettings.asset
  VR_Polytechnique/Packages/manifest.json
  VR_Polytechnique/Packages/packages-lock.json
  VR_Polytechnique/ProjectSettings/EditorBuildSettings.asset
  VR_Polytechnique/ProjectSettings/PresetManager.asset
  VR_Polytechnique/UserSettings/EditorUserSettings.asset
  VR_Polytechnique/UserSettings/Layouts/default-2021.dwlt
Labels: enhancement

#10 Permet de ne pas track les UserSettings
  .gitignore
  VR_Polytechnique/UserSettings/EditorUserSettings.asset
  VR_Polytechnique/UserSettings/Layouts/default-2021.dwlt
  VR_Polytechnique/UserSettings/Search.settings
Labels: bug

#16 Ajout du CAD de la ville avec les dimensions et d'une version PDF
  Documents/Plan VR 1 - Dimension exacte.pdf
  Documents/Plan VR 1 - Dimensions exactes.bak
  Documents/Plan VR 1 - Dimensions exactes.dwg
  Documents/Plan VR 1.bak
  Documents/Plan VR 1.dwg
Labels: documentation

#14 Ajout d'un menu de pause
  VR_Polytechnique/Assets/Prefabs/Menu/MenuCanvas.prefab
  VR_Polytechnique/Assets/Prefabs/Menu/MenuCanvas.prefab.meta
  VR_Polytechnique/Assets/Scenes/Menu_Anglais.unity
  VR_Polytechnique/Assets/Scenes/Menu_Français.unity
  VR_Polytechnique/Assets/Scenes/Mode_Apprentissage.unity
  VR_Polytechnique/Assets/Scenes/Mode_Evaluation.unity
  VR_Polytechnique/Assets/Scripts/PauseMenu.cs
  VR_Polytechnique/Assets/Scripts/PauseMenu.cs.meta
  VR_Polytechnique/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/LiberationSans SDF - Metalic Green.mat
  VR_Polytechnique/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
  VR_Polytechnique/ProjectSettings/EditorBuildSettings.asset
  VR_Polytechnique/ProjectSettings/ProjectSettings.asset
Labels: enhancement

#22 Ajout de XR settings dans le gitignore
  .gitignore
Labels: bug

#12 <Fonctionnalité de mouvement dans la scene base et délétion de la scene Camera&Mouvement>
  VR_Polytechnique/Assets/Scenes/Camera&Movement.unity
  VR_Polytechnique/Assets/Scenes/Camera&Movement.unity.meta
  VR_Polytechnique/Assets/Scenes/Mode_Apprentissage.unity
  VR_Polytechnique/Assets/Scenes/Mode_Evaluation.unity
Labels: enhancement

#25 Sauvegarde en format Json
  VR_Polytechnique/Assets/Prefabs/DataPersistenceManager.prefab
  VR_Polytechnique/Assets/Prefabs/DataPersistenceManager.prefab.meta
  VR_Polytechnique/Assets/Prefabs/Menu/LanguageButton.prefab
  VR_Polytechnique/Assets/Prefabs/Menu/StartButton.prefab
  VR_Polytechnique/Assets/Prefabs/Menu/TutorielButton.prefab
  VR_Polytechnique/Assets/Prefabs/Menu/VolumeSlider.prefab
  VR_Polytechnique/Assets/Scenes/Menu_Anglais.unity
  VR_Polytechnique/Assets/Scenes/Menu_Fin_Anglais.unity
  VR_Polytechnique/Assets/Scenes/Menu_Fin_Français.unity
  VR_Polytechnique/Assets/Scenes/Menu_Français.unity
  VR_Polytechnique/Assets/Scenes/Mode_Apprentissage.unity
  VR_Polytechnique/Assets/Scenes/Mode_Evaluation.unity
  VR_Polytechnique/Assets/Scripts/DataPersistence.meta
  VR_Polytechnique/Assets/Scripts/DataPersistence/Data.meta
  VR_Polytechnique/Assets/Scripts/DataPersistence/Data/GameData.cs
  VR_Polytechnique/Assets/Scripts/DataPersistence/Data/GameData.cs.meta
  VR_Polytechnique/Assets/Scripts/DataPersistence/DataPersistenceManager.cs
  VR_Polytechnique/Assets/Scripts/DataPersistence/DataPersistenceManager.cs.meta
  VR_Polytechnique/Assets/Scripts/DataPersistence/FileDataHandler.cs
  VR_Polytechnique/Assets/Scripts/DataPersistence/FileDataHandler.cs.meta
  VR_Polytechnique/Assets/Scripts/DataPersistence/IDataPersistence.cs
  VR_Polytechnique/Assets/Scripts/DataPersistence/IDataPersistence.cs.meta
  VR_Polytechnique/Assets/Scripts/DataPersistence/SerializableTypes.meta
  VR_Polytechnique/Assets/Scripts/DataPersistence/SerializableTypes/SerilizableDictionary.cs
  VR_Polytechnique/Assets/Scripts/DataPersistence/SerializableTypes/SerilizableDictionary.cs.meta
  VR_Polytechnique/Assets/Scripts/MenuFinManager.cs
  VR_Polytechnique/Assets/Scripts/MenuManager.cs
  VR_Polytechnique/Assets/Scripts/MenuScripts.meta
  VR_Polytechnique/Assets/Scripts/MenuScripts/MenuFinManager.cs
  VR_Polytechnique/Assets/Scripts/MenuScripts/MenuFinManager.cs.meta
  VR_Polytechnique/Assets/Scripts/MenuScripts/MenuManager.cs
  VR_Polytechnique/Assets/Scripts/MenuScripts/MenuManager.cs.meta
  VR_Polytechnique/Assets/Scripts/MenuScripts/PauseMenu.cs
  VR_Polytechnique/Assets/Scripts/MenuScripts/PauseMenu.cs.meta
  VR_Polytechnique/Assets/Scripts/MenuScripts/VolumeSlider.cs
  VR_Polytechnique/Assets/Scripts/MenuScripts/VolumeSlider.cs.meta
  VR_Polytechnique/Assets/Scripts/Timer.cs
  VR_Polytechnique/Assets/Scripts/TimerText.cs
  VR_Polytechnique/Assets/Scripts/TimerText.cs.meta
Labels: enhancement

#26 Ajout d'un relief et d'arbre en background
  VR_Polytechnique/Assets/Design/Conifers [BOTD]/Render Pipeline Support/URP/Prefabs URP/PF Conifer Tall BOTD URP.prefab
  VR_Polytechnique/Assets/Design/Conifers [BOTD]/Render Pipeline Support/URP/Sources URP/Billboards URP/Conifer Bare_BillboardMaterial URP.mat
  VR_Polytechnique/Assets/Design/Conifers [BOTD]/Render Pipeline Support/URP/Sources URP/Billboards URP/Conifer Small_BillboardMaterial URP.mat
  VR_Polytechnique/Assets/Design/Conifers [BOTD]/Render Pipeline Support/URP/Sources URP/Billboards URP/Conifer Tall_BillboardMaterial URP.mat
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_1d34a8c8-cdae-4383-b685-a7a72664ca76.asset
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_1d34a8c8-cdae-4383-b685-a7a72664ca76.asset.meta
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_49fe726c-c463-49a7-9467-8a39b8de261d.asset
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_49fe726c-c463-49a7-9467-8a39b8de261d.asset.meta
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_4c4dbdf9-ae35-45c9-9662-59e562739b1c.asset
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_4c4dbdf9-ae35-45c9-9662-59e562739b1c.asset.meta
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_5421beae-2536-4b8e-97bb-9a3d17028fe9.asset
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_5421beae-2536-4b8e-97bb-9a3d17028fe9.asset.meta
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_73548c50-a311-4bb8-8ae1-25cbb2c555eb.asset
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_73548c50-a311-4bb8-8ae1-25cbb2c555eb.asset.meta
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_99cdb032-0957-4325-803d-37d47580065e.asset
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_99cdb032-0957-4325-803d-37d47580065e.asset.meta
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_9ad27a66-5301-4436-bd3a-5a41c6235aa4.asset
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_9ad27a66-5301-4436-bd3a-5a41c6235aa4.asset.meta
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_a18d3290-045e-4a78-ab24-5dae02314b0d.asset
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_a18d3290-045e-4a78-ab24-5dae02314b0d.asset.meta
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_ab3b34f5-0417-405d-8e9b-886682d92785.asset
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_ab3b34f5-0417-405d-8e9b-886682d92785.asset.meta
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_b505b4a4-735a-432d-a81e-ebc8396cb949.asset
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_b505b4a4-735a-432d-a81e-ebc8396cb949.asset.meta
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_bb34bfc9-28d5-4349-b041-908d67706123.asset
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_bb34bfc9-28d5-4349-b041-908d67706123.asset.meta
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_bcfcc42f-dd9b-433b-b769-a3b6552c132d.asset
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_bcfcc42f-dd9b-433b-b769-a3b6552c132d.asset.meta
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_d3baf938-b2a7-4e84-8ac0-1f9687bad0a5.asset
  VR_Polytechnique/Assets/Design/Terrain/TerrainData_d3baf938-b2a7-4e84-8ac0-1f9687bad0a5.asset.meta
  VR_Polytechnique/Assets/Design/Terrain/Terrain_0_0_fd98077a-bab1-4d01-8add-c8c425edb54b.asset
  VR_Polytechnique/Assets/Design/Terrain/Terrain_0_1_73e56586-4ac8-41d7-bd7a-2fefe8bca023.asset
  VR_Polytechnique/Assets/Design/Terrain/Terrain_1_0_d84ad7ba-9971-438b-8dff-1566fd0c59b9.asset
  VR_Polytechnique/Assets/Design/Terrain/Terrain_1_1_2ad7c227-2409-4a9a-b4de-97b860295e67.asset
  VR_Polytechnique/Assets/Scenes/Mode_Evaluation.unity
Labels: enhancement
